name: OCR Tool CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-en-us libhunspell-dev
          # Verify hunspell installation
          hunspell -v
          # Show installed library location
          ldconfig -p | grep hunspell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint and Test
        run: |
          python -m unittest discover
      - name: Build Docker image
        run: |
          docker build -t ocr_pdf_tool .
      - name: Push Docker image (optioneel)
        run: echo "Add Docker Hub credentials here"